# Project information
site_name: Portfolio
site_url: https://mohitsainiknl.github.io/
site_author: Mohit Saini
site_description: >-
  Website for My Portfolio - MohitSainiKnl

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon-32x32.png
  logo: assets/logo-32x32.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list


extra_css:
  - stylesheets/extra.css
  - stylesheets/owl.carousel.min.css
  - stylesheets/owl.theme.default.min.css
  - stylesheets/carousel.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/jquery-3.6.0.min.js
  - javascripts/owl.carousel.min.js
  - javascripts/carousel.js

# nav:
#   - Home: index.md
#   - Education: education.md
#   - Experience: experience.md
#   - Projects: projects.md
#   - Contacts: contacts.md
